Update readme.md
CodeYourFuture/Module-Databases pull request #19
Opened 2023-04-16 06:48 UTC by SallyMcGrath

-- add date check
-- add stemming cue
-- add names conversation

2023-04-16 10:43 UTC, KeithBremer commented
Looks good.  The final request, to add a new transaction requires several (possible) selects and inserts - it might be helpful to provide a hint to trainees as:
INSERT YOUR QUERY/QUERIES HERE
in the response box.

2023-04-16 14:12 UTC, KeithBremer requested changes

2023-04-16 14:12 UTC, KeithBremer commented on Big-Spender/readme.md
Looks good. The final request, to add a new transaction requires several inserts and possibly selects - it might be helpful to provide a hint to trainees as:
INSERT YOUR QUERY/QUERIES HERE
in the response box.

2023-04-23 21:02 UTC, illicitonion approved these changes

2023-04-24 10:59 UTC, KeithBremer approved these changes

2023-04-24 14:25 UTC, merged